name: UI check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        # See https://docs.docker.com/engine/install/ubuntu/
        run: |
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
          sudo apt remove docker docker-engine docker.io containerd runc
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt update
          sudo apt-cache policy docker-ce
          sudo apt install docker-ce containerd.io

      - name: Docker build and run
        run: |
          sudo docker build -t qlever-ui ${{github.workspace}}
          docker run --it -d -v $(pwd)/db:/app/db --name qlever-ui qlever-ui

      - name: End-to-end test
        run: |
          python3 end2end-test.py --url http://localhost:7000
          docker rm -f qlever-ui
